// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Next.js convention: .env.local beats .env (boilerplate dummy creds). Load in that
// order so prisma CLI sees the real DATABASE_URL from .env.local.
import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local", override: false });
loadEnv({ path: ".env", override: false });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Prisma 7: package.json'daki `prisma.seed` artık yok sayılıyor; seed config
    // buraya taşındı. Generated client ES modülü olduğu için ts-node yerine
    // tsx kullanıyoruz (node 20+ ile uyumlu, ESM TS runner).
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
